#work flow라고 불리는 yml 파일
name: Github Actions 실행시켜보기
# work flow 이름.
on:
#  event
  push:
    branches:
      - main

jobs:
  My-depoly-job:
    runs-on: ubuntu-latest

    steps:
      - name: Hellow world 찍기
        run: echo "hello world"

      - name: 여러 명령어 작성하기
        run: | 
          echo "Good"
          echo "Morning"

      - name: Github Actions 자체에 저장되어 있는 변수 사용해보기
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY