name: first-yml

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-lastest

    steps:
      - name: first
        run: echo "hello world"

      - name: second
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY